//
//  GCDTestViewController.swift
//  GCD
//
//  Created by Ivan Peña on 3/16/19.
//  Copyright (c) 2019 Multiplica. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GCDTestDisplayLogic: class
{
  
}

class GCDTestViewController: UIViewController, GCDTestDisplayLogic
{
    var interactor: GCDTestBusinessLogic?
    var router: (NSObjectProtocol & GCDTestRoutingLogic & GCDTestDataPassing)?
    
    

    // MARK: Object lifecycle
  
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
  
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
  
    // MARK: Setup
  
    private func setup()
    {
        let viewController = self
        let interactor = GCDTestInteractor()
        let presenter = GCDTestPresenter()
        let router = GCDTestRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
  
    // MARK: View lifecycle
  
    override func viewDidLoad()
    {
        super.viewDidLoad()
        
    }
  
    @IBAction func testButtonAction(_ sender: UIButton) {
        interactor?.gcdTest()
    }
    
    
}
