//
//  GCDTestPresenter.swift
//  GCD
//
//  Created by Ivan Peña on 3/16/19.
//  Copyright (c) 2019 Multiplica. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GCDTestPresentationLogic
{
  
}

class GCDTestPresenter: GCDTestPresentationLogic
{
    weak var viewController: GCDTestDisplayLogic?
  
  
}
