//
//  GCDTestRouter.swift
//  GCD
//
//  Created by Ivan Peña on 3/16/19.
//  Copyright (c) 2019 Multiplica. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol GCDTestRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol GCDTestDataPassing
{
  var dataStore: GCDTestDataStore? { get }
}

class GCDTestRouter: NSObject, GCDTestRoutingLogic, GCDTestDataPassing
{
  weak var viewController: GCDTestViewController?
  var dataStore: GCDTestDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: GCDTestViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: GCDTestDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
